{{ define "fhi.application.yaml"}}
appconfig:
{{- with (first .Values.ingress.hosts) }}
   hostname: {{ .host }}
{{- end }}

eureka:
   instance:
      statusPageUrl: https://${appconfig.hostname}/actuator/info
      healthCheckUrl: https://${appconfig.hostname}/actuator/health
      homePageUrl: https://${appconfig.hostname}/
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: {{ .Values.eureka.defaultZone }}
server:
   use-forward-headers: true
   servlet:
      context-path: /
      
#logging:
#    level:
#        de.oc.dai.emst2.fhi.services.ClientLoggerService: WARN
        
spring:
   application:
      name: {{ .Release.Name }}
   datasource:
      password: {{ .Values.spring.datasource.password }}
      username: {{ .Values.spring.datasource.username }}
      url: {{ .Values.spring.datasource.url }}
   profiles: 
      active:
         {{- range $profiles := .Values.profiles.active }}
         - {{ . }}
         {{- end }}
         
keycloak:
{{ toYaml .Values.keycloak | indent 2 }}
{{ end }}
