spring:
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    validationQuery: 'SELECT 1 FROM DUAL'
    hikari:
      poolName: fhi_cp
      minimumIdle: 5
      maximumPoolSize: 10
      registerMbeans: true
keycloak:
    principal-attribute: preferred_username
    use-resource-role-mappings: true
