# Default values for fhi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.emst.opitz-consulting.int/emst/fhi-emst2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

### DINA Config ####
eureka:
  hostname: vsdlgm198.opitz-consulting.int
  defaultZone: https://vsdlgm198.opitz-consulting.int/eureka/eureka

#sma:
#  datasource:
#    password: plf_dev
#    username: plf_dev
#    jdbcUrl: jdbc:oracle:thin:@vsdlgm202:1521:ZSM

spring:
  datasource:
    password: fhi_ci
    username: fhi_ci
    url: jdbc:oracle:thin:@vsdlgm200.opitz-consulting.int:1521:fhi060

#profiles: 
#  active: 
#    - zebra-mock
#    - kas_mock
#    - sma_mock

keycloak:
  realm: "060"
  auth-server-url: https://vsdlgm198.opitz-consulting.int/auth/
  ssl-required: none
  resource: emst2-fhi
  public-client: true
  disable-trust-manager: true
#############

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "fhi-emst2"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: fhi.emst.opitz-consulting.int
      paths:
        - /
        
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
