name: Comment PR

on:
  pull_request:
    types: [opened]

jobs:
  setup:
    runs-on: nodejs
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: full export
        run: export
      - name: Write URL to PR
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          PR_KUBE_LINK: https://fhi-emst2-pr-${{ github.event.number }}-emst${{ secrets.K8S_DEV_URL_SUFFIX }}
        run: |
          curl -X POST $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "The current PR is '"$PR_NUMBER"'. Visit here: [FHI PR-Link]('"$PR_KUBE_LINK"')" }'
